name: deploy hugo site

# Controls when the action will run. 
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-18.04
    
    # steps는 명령어들의 집합
    # uses는 이미 만들어진 action을 사용, run은 명령어를 실행하는 것
    steps:
    
    #1. 가상머신으로 checkout
    - uses: actions/checkout@v2
      with:
        submodules: true
          
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        
    - name: Build Hugo Site
      run: hugo --minify
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
